require('./db.js');
const express = require('express');
const port = process.env.Port || 7000 ;
const app = express();
app.use(express.urlencoded({ extended: true }));
app.use(express.json());
const medecin_router = require('./routers/medecins');
const ord_router= require('./routers/ordonnances');
const pharmacie_router = require('./routers/pharmacies');
const patient_router = require('./routers/patients');
const livreur_router = require('./routers/livreurs');
const commande_router = require('./routers/commandes');
app.use('/api/medecin',medecin_router);
app.use('/api/ord',ord_router);
app.use('/api/patient',patient_router);
app.use('/api/pharmacie',pharmacie_router);
app.use('/api/livreur',livreur_router);
app.use('/api/commande',commande_router);
app.listen(port,()=>console.log('Server on', port ));
